---
# file: tasks/raid.yml
# Configure a RAID on a remote machine in the testbed

- name: Install mdadm
  sudo: yes
  apt: name=mdadm state=present update_cache=yes

# - name: Setting up software raid
#   sudo: yes
#   debug: var=ebs_volumes

# - debug: var=raid_type

- name: "Check for existing device: /dev/md0 - allowed to echo errors"
  sudo: yes
  command: "mdadm -D {{ sutdevice }}"
  ignore_errors: yes
  register: dev_exists


# ebs_volume_list|length
# --raid-devices=2 /dev/xvdb /dev/xvdc"
- name: "Create device: /dev/md0"
  sudo: yes
  command: "mdadm --create {{ sutdevice }} --auto md --level={{ raid_level }} --chunk={{ raid_chunksize }} --raid-devices={{ ebs_volume_list|length }} {{ ebs_volume_list|join(' ') }}"
  when: dev_exists.rc != 0

- include: mounted_dev.yml